# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
  - job: OS
    pool:
      vmImage: 'macOS-latest'
    steps:
    - task: FlutterInstall@0
    - task: FlutterBuild@0
      inputs:
        target: 'all'
        projectDirectory: '.'
        iosCodesign: false    
        iosTargetPlatform: 'simulator'
    - task: PublishBuildArtifacts@1