# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

FIREBASE_TOKEN = ENV['FIREBASE_TOKEN']
default_platform(:android)
platform :android do
  desc "Deploy a new beta"
  lane :distribute_beta do
      firebase_app_distribution(
          app: "1:465095271141:android:a3a731af961f5e6555ea0c",
          release_notes: "Primera build de GoingTo, ¿Que esperas para probarla?",
          firebase_cli_path: "/usr/local/bin/firebase",
          firebase_cli_token: "1//0hA64-Ag0HiTfCgYIARAAGBESNwF-L9IrJQu5XNgBqE5fpUJNIEcZ9GakZsi24-Qb0RPfEXBs5zHuh_yvm2-oirnA_W3Fhev7L8o",
          testers: "lporteniu@gmail.com,marioneta03@gmail.com",
          apk_path: "../build/app/outputs/apk/release/app-release.apk"
      )
  end
end

# Lo que se genero al inicio (?)
# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end

#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
  
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end

#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end
